### ISSUE TITLE
Failed to generate schema: illegal token '.items.message.required'

### ISSUE THREAD

**Issue by dvdthecoder** [protobufjs/protobuf.js#1683]
protobuf.js version: <please fill in>
^3.19.1
<please describe the expected and actual behavior>
When we try to use the proto definitions provided as here https://buf.build/authzed/api/file/main/authzed/api/v1/permission_service.proto , the parsing is failing with error as shown fo   [ (validate.rules).repeated .items.message.required = true ]; definition with the proto file
<please provide a code snippet for reproduction>
```
Trying to run transformation to GraphQL services of a GRPC proto using https://github.com/Urigo/graphql-mesh 
sources:
  name: Authzed-gRPC
    handler:
      grpc:
        endpoint: localhost:50051
        useHTTPS : false
        useReflection: true
        metaData:
          Authorization: 'somerandomkey'
        protoFilePath:
          file: ./proto/authzed/api/v1/permission_service.proto
          load:
            includeDirs:
              - ./proto
    transforms:
      - namingConvention:
          fieldNames: camelCase   
```
<please paste the stack trace of the error if applicable>
Loading proto files(./proto/authzed/api/v1/permission_service.proto); 
 ./proto/authzed/api/v1/permission_service.proto 
🕸️ - Authzed-gRPC: Failed to generate schema: illegal token '.items.message.required', '=' expected (line 199)
🕸️ - Authzed-gRPC: Error: illegal token '.items.message.required', '=' expected (line 199);
 Error: illegal token '.items.message.required', '=' expected (line 199)
    at illegal (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/tokenize.js:124:16)
    at skip (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/tokenize.js:365:19)
    at parseOption (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:584:9)
    at parseInlineOptions (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:638:17)
    at parseField_line (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:388:13)
    at ifBlock (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:294:17)
    at parseField (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:378:9)
    at parseType_block (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:320:21)
    at ifBlock (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:290:17)
    at parseType (/Users/abhishekdwivedi/programming/node/graphql_mesh/node_modules/protobufjs/src/parse.js:308:9)
